title: NFDI4Microbiota Knowledge Base
author:
  name: 'Github User'
  email: 'github@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: /nfdi4microbiota-knowledge-base

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  #header_pages:
  # - about.md

  # generate social links in footer
  social_links:
    mastodon: 'https://nfdi.social/@NFDI4Microbiota'
    github:  'https://github.com/NFDI4Microbiota'


# Build settings
exclude:
  - node_modules
remote_theme: jonaharagon/jekyll-bootstrap-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-scholar
markdown: Kramdown
collections_dir: docs
collections:
  Getting-Started:
    output: true
    permalink: /:collection/:name
    order: 1
  Research-Data-Management:
    output: true
    permalink: /:collection/:name
    order: 2
  RDM-Plan:
    output: true
    permalink: /:collection/:name
    order: 3
  RDM-Collect:
    output: true
    permalink: /:collection/:name
    order: 4
  RDM-Process:
    output: true
    permalink: /:collection/:name
    order: 5
  RDM-Preserve:
    output: true
    permalink: /:collection/:name
    order: 6
  RDM-Share:
    output: true
    permalink: /:collection/:name
    order: 7
  RDM-Reuse:
    output: true
    permalink: /:collection/:name
    order: 8
  Reproducible-Data-Analysis:
    output: true
    permalink: /:collection/:name
    order: 9
  Software-Development:
    output: true
    permalink: /:collection/:name
    order: 10
  Experimental-Procedure-Standards-SOPs:
    output: true
    permalink: /:collection/:name
    order: 11
  Resources:
    output: true
    permalink: /:collection/:name
    order: 12
  How-We-Operate:
    output: true
    permalink: /:collection/:name
    order: 13

# Plugin settings
scholar:
# Numeric style like american-medical-association causes duplication in numbering of the references
# So enforcing a author-year style
  style: apa
  source: ./docs/_bibliography
