name: Build and Deploy to Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: zbmed-self-hosted

    steps:
      - name: Checkout repository with correct permissions
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: echo $SUDO_PASS | sudo -S -u elhossary git clone --depth=0 https://github.com/NFDI4Microbiota/nfdi4microbiota-knowledge-base.git .

      - name: Build Jekyll site with Docker
        run: |
          docker run --rm -v $PWD:/srv/jekyll -v $PWD/vendor/bundle:/usr/local/bundle jekyll/jekyll:latest jekyll build -d _site

      - name: Copy site data to the serving directory
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: |
          rm -rf /var/www/kb-nfdi4microbiota/* && cp -r $PWD/_site/* /var/www/kb-nfdi4microbiota/
