name: Build and Deploy to Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: zbmed-self-hosted

    steps:
      - name: Acquire ownership permissions
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: echo $SUDO_PASS | sudo -S chown -R elhossary:elhossary $PWD/../../*

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Jekyll site with Docker
        run: docker run --rm -v "$PWD:/srv/jekyll" -v "$PWD/_site:/srv/jekyll/_site" jekyll/jekyll:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build -d _site"

      - name: Copy site data to the serving directory
        env:
          SUDO_PASS: ${{ secrets.ELHOSSARY_SUDO_PASSWORD }}
        run: |
          rm -rf /var/www/kb-nfdi4microbiota/* && cp -r $PWD/_site/* /var/www/kb-nfdi4microbiota/
