name: Deploy Jekyll to Self-hosted Runner

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Jekyll site using Docker
        run: |
          sudo docker run --rm --user $(id -u):$(id -g) \
            -v "${{ github.workspace }}":/srv/jekyll \
            -w /srv/jekyll \
            jekyll/jekyll jekyll build

      - name: Determine target directory
        id: deploy-path
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TARGET_DIR=/var/www/production/knowledgebase.nfdi4microbiota.de" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "TARGET_DIR=/var/www/development/knowledgebase.nfdi4microbiota.de" >> $GITHUB_ENV
          else
            echo "Skipping deployment for unrecognized branch"
            exit 1
          fi

      - name: Deploy to target directory
        if: github.event_name == 'push'
        run: |
          sudo rm -rf $TARGET_DIR/*
          sudo cp -r _site/* $TARGET_DIR/
          sudo chown -R www-data:www-data $TARGET_DIR
          sudo chmod -R 755 $TARGET_DIR

      - name: Clean Up Workspace
        if: always()
        run: |
          echo "Cleaning up workspace..."
          rm -rf $GITHUB_WORKSPACE/*
          echo "Cleanup complete."
          sudo docker system prune -f
