name: Spellcheck Action

on:
  # Runs on pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.36.0
      name: Spellcheck
      with:
        extra_args: --wordlist .github/workflows/spellcheck.whitelist
